# .github/workflows/docker-image.yml
name: Build and push Docker image to Azure Container Registry

# Trigger on push to the main branch
on:
  workflow_dispatch:
  push:
    branches:
      - main

# Define variables
env:
  AZURE_CONTAINER_REGISTRY: 'mypythonacr31098.azurecr.io'
  IMAGE_NAME: 'pythonappdocker'
  TAG: '${{ github.sha }}'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Azure Container Registry
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    # Step 3: Build and push the Docker image
    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

    # Step 4: Archive the source files
    - name: Archive source files
      uses: actions/upload-artifact@v3
      with:
        name: source-code
        path: |
          .
